### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by InjuMichorius** [StanBankras/chart-sync#1]
### Repository scan
**Does the repo have an apt description?**
Yes, the readme is well documentated, maybe it's an idea to push your sketches to your wiki once you've progressed more.
**Is there a link to the live demo at the top?**
No
**Are any files in the repo that shouldn't be there like an .env file or node_modules?**
No, the repo contains a nice gitignore file
**Is there a section about the concept, install notes, data life cycle, external API, and real-time events?**
Yes, this part is very well explained, especialy the api.

### Understanding the concept
**Read about the concept in the readme, do you understand what the app does?**
I might be biased, because you've already explained the concept to me, but the concept is very clear and well needed

### Data life cycle
**Are all the app's components present in a visual diagram?**
Yes, it's very visible and accessible. Maybe you can make the white text a little bigger but it's clear to me where the data is going
**Is it clear what data is stored for each component?**
Not in the visual representation, but the explanation covers everything pretty well. The image should just give you a global idea imo.
**Is it clear how components communicate with each other? (socket, polling, OAuth)**
Yes, aldo I do wonder if it would be a better idea to seperate your server and socket.
**Can you follow where real-time data is created?**
Sorta, the socket.io doesn't really stand out.

### Real-time events
**Are all custom events described?**
No, but the explanation tells me what he's using (but I don't really know what for).

### API information
**Is it clear what data the external API offers?**
Couldn't be more clear
**Are instructions present on how to get a key from the API and how to connect to it?**
Not in great detail, but the readme does give a endpoint and a documentation link (that should be enough)

### Conclusion
- The application is very cool! I wish I could see it, but there is no link yet :(
- Maybe seperate your server and socket to get into the data a little bit more.
- The code is obviously well written, wouldn't expect otherwise.
- Add some things in your readme or wiki where you explain what you're doing with the data

**Comment by standrd** [comment]
Thanks Inju. I updated my readme with more information based on your feedback.
