### ISSUE TITLE
Room code suggestion

### ISSUE THREAD

**Issue by RowinRuizendaal** [StanBankras/chart-sync#12]
When making a new room I get this as room code : Cool-charter-250 - fcfd4d58-9f99-4b1f-949c-0c311003d6ca, but since only the last part of this works: fcfd4d58-9f99-4b1f-949c-0c311003d6ca, why not strip the Cool-charter-250 - part of the code? :)

**Comment by standrd** [comment]
This is a good suggestion, but there could be duplicate ids if I use this room code. In the long run, this will probably cause issues. Of course I could check if an ID already exists, but there is not enough time for me to do this at this point anymore.
