### ISSUE TITLE
optional: adding chart in room

### ISSUE THREAD

**Issue by RowinRuizendaal** [StanBankras/chart-sync#13]
So for instance, if I think I need a single chart, but I discover later that I will need more charts to compare a specific currency or w/e I have to make a new room that supports multiple charts.

I think this should be a good feature for your app, but I think it should be on your MOSCOW list :)

**Comment by standrd** [comment]
It actually is one of my could haves:
"Change chart layout"

But I agree it could be a bit better formatted to cover the meaning better! Thanks.
