### ISSUE TITLE
Functionalities

### ISSUE THREAD

**Issue by RowinRuizendaal** [StanBankras/chart-sync#6]
Ik zie dat je een lijst bij houdt van de Functionalities, dit is nice alleen is dit een lijst van functionaliteiten die er al in zitten of die er voor de helft in zit? Misschien kan je bij de functionaliteiten die er al in zitten een x in zetten, wellicht geeft dat een beter overzicht van wat de app kan en wat je nog wil maken of wat er nog op de long list staat.

**Comment by standrd** [comment]
Dit heb ik nu gedaan, goed idee! Thanks.
